import type { Account, AppSettings, AssetCategory } from './types';
import { DEFAULT_THEME_ID } from './themes';

export const APP_VERSION = '1.1.0';

const SEED_TIMESTAMP = '2026-05-20T08:00:00.000Z';

export const DEFAULT_CATEGORIES: AssetCategory[] = [
  {
    id: 'bank',
    name: '银行卡',
    shortName: '银行',
    icon: 'card',
    isNegative: false,
    active: true,
    sortOrder: 10,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'payment',
    name: '支付平台',
    shortName: '支付',
    icon: 'wallet',
    isNegative: false,
    active: true,
    sortOrder: 20,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'stock',
    name: '股票',
    shortName: '股票',
    icon: 'screen',
    isNegative: false,
    active: true,
    sortOrder: 30,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'cash',
    name: '现金',
    shortName: '现金',
    icon: 'cash',
    isNegative: false,
    active: true,
    sortOrder: 40,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'liability',
    name: '负债',
    shortName: '负债',
    icon: 'credit',
    isNegative: true,
    active: true,
    sortOrder: 50,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  currency: 'CNY',
  hideAmounts: false,
  deductNegativeAssets: true,
  themeId: DEFAULT_THEME_ID,
  lastBackupAt: null,
  appVersion: APP_VERSION,
};

export const SEED_ACCOUNTS: Account[] = [
  {
    id: 'cmb-bank',
    name: '招商银行',
    category: 'bank',
    balance: 63206.32,
    includeInTotal: true,
    note: '工资卡与活期',
    sortOrder: 10,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'alipay',
    name: '支付宝',
    category: 'payment',
    balance: 1970.8,
    includeInTotal: true,
    note: '',
    sortOrder: 20,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'wechat',
    name: '微信',
    category: 'payment',
    balance: 0,
    includeInTotal: true,
    note: '',
    sortOrder: 30,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'stock',
    name: '股票账户',
    category: 'stock',
    balance: 27802.5,
    includeInTotal: true,
    note: '',
    sortOrder: 40,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'cash',
    name: '现金',
    category: 'cash',
    balance: 102136.42,
    includeInTotal: true,
    note: '',
    sortOrder: 50,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: 'credit-card',
    name: '信用卡',
    category: 'liability',
    balance: 0,
    includeInTotal: true,
    note: '',
    sortOrder: 70,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];
